# Generated by Django 3.1.1 on 2020-09-07 13:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='nickname',
            field=models.CharField(default='', max_length=10, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
    ]
