# Generated by Django 3.1.1 on 2020-09-07 13:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200907_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='nickname',
            field=models.CharField(default='', max_length=10, validators=[django.core.validators.RegexValidator(code='nomatch', message='Length has to be 2', regex='^.{2}$')]),
        ),
    ]
