# Generated by Django 3.1.1 on 2020-09-09 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='imageURL',
        ),
    ]
