# Generated by Django 3.1.1 on 2020-09-10 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_profile_imageurl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='example',
        ),
    ]
