# Generated by Django 3.1 on 2020-09-29 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='director',
            old_name='imageURL',
            new_name='image_url',
        ),
        migrations.RenameField(
            model_name='production',
            old_name='imageURL',
            new_name='image_url',
        ),
        migrations.AddField(
            model_name='director',
            name='sns_link',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='production',
            name='sns_link',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
