# Generated by Django 3.1.1 on 2020-10-05 10:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='director',
            old_name='imageURL',
            new_name='image_url',
        ),
        migrations.RenameField(
            model_name='production',
            old_name='imageURL',
            new_name='image_url',
        ),
        migrations.AddField(
            model_name='director',
            name='sns_link',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
