# Generated by Django 3.1 on 2020-09-29 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicvideo',
            name='upload_date',
            field=models.DateTimeField(null=True),
        ),
    ]
