# Generated by Django 3.0.8 on 2020-07-29 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicvideo',
            name='video_link',
            field=models.CharField(default='3w5iMGSHvsE', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='mv.MusicVideo'),
        ),
    ]
